// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Suave")>]
[<assembly: AssemblyDescriptionAttribute("Suave — a smooth, open source, F# web server.")>]
[<assembly: AssemblyVersionAttribute("2.4.3")>]
[<assembly: AssemblyFileVersionAttribute("2.4.3")>]
[<assembly: AssemblyMetadataAttribute("Commit","2d1ad8")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Suave"
    let [<Literal>] AssemblyDescription = "Suave — a smooth, open source, F# web server."
    let [<Literal>] AssemblyVersion = "2.4.3"
    let [<Literal>] AssemblyFileVersion = "2.4.3"
    let [<Literal>] AssemblyMetadata_Commit = "2d1ad8"
